#!/bin/bash
set -vxeuo pipefail

COMMIT=$(git rev-parse HEAD)
TAG=$(git describe --exact-match --abbrev=0 --tags "${COMMIT}" 2> /dev/null || true)
OUTPUT_PATH=${OUTPUT_PATH:-"bin/oauth2clientweb"}

if [ -z "$TAG" ]; then
   VERSION=$COMMIT
else
	VERSION=$TAG
fi

# check for changed files (not untracked files)
if [ -n "$(git diff --shortstat 2> /dev/null | tail -n1)" ]; then
    VERSION="${VERSION}+dirty"
fi

echo Building kube-selenium ${VERSION}

if [[ ! "${BUILD_GOOS:-}" == "" ]];then
  export GOOS=$BUILD_GOOS
fi
if [[ ! "${BUILD_GOARCH:-}" == "" ]];then
  export GOARCH=$BUILD_GOARCH
fi

pwd

go build -ldflags "-X github.com/mumoshu/kube-distributed-test/testdep/oauth2clientweb/main.VERSION=${VERSION}" -a -tags netgo -installsuffix netgo -o "$OUTPUT_PATH" ./
chmod +x $OUTPUT_PATH
