#!/bin/bash -e

# Add OS support here
# Add "darwin" for macOS build
for os in linux darwin; do
    # Add architecture support here
    for arch in amd64;do
    output_folder="${os}-${arch}"
    rm -rf "$output_folder"
    mkdir "$output_folder"
    echo "Building kube-selenium for GOOS=${os} GOARCH=${arch}"
    OUTPUT_PATH="$output_folder/oauth2clientweb" BUILD_GOOS=$os BUILD_GOARCH=$arch ./hack/build

    releaseTar=kube-selenium-"${os}-${arch}".tar.gz
    rm -rf "$releaseTar"
    tar czvf $releaseTar "$output_folder"
    #rm -rf "$output_folder"
    echo "${os}-${arch} --> ${releaseTar}"
    done
done
echo "Done!"
